// fcp_v2_assets/languages.js
// SannaStudio'Prod — Traductions françaises uniquement

export const translations = {
    fr: {
        appTitle: "SannaStudio'Prod — Tableau de Bord Football V2.9.1",
        excel: "Excel",
        matchId: "ID :",
        load: "Charger",
        teamA: "Équipe A",
        teamB: "Équipe B",
        edit: "Modifier",
        editHint: "Modifier le nom ou ajouter une ligne avec /",
        ok: "OK",
        label1: "Étiquette 1",
        label2: "Étiquette 2",
        label3: "Étiquette 3",
        label4: "Étiquette 4",
        label5: "Étiquette 5",
        label6: "Étiquette 6",
        swap: "Inverser les équipes",
        reset: "Réinitialiser",
        fullReset: "Réinitialiser",
        score2Label: "Fautes / Compteur",
        hide: "Masquer",
        show: "Afficher",
        score2VisibilityGroup: "Affichage Score 2",
        swapCardVisibility: "Affichage carte d'inversion",
        actionCardVisibility: "Affichage boutons d'action",
        labelCount: "Nb d'étiquettes :",
        visibilityTitle: "Contrôle d'affichage des cartes",
        resetKeybinds: "Réinitialiser les raccourcis",
        resetColors: "Effacer les couleurs d'équipe",
        half: "Mi-temps",
        injuryTime: "Temps additionnel",
        countdown: "Décompte",
        countdownHint: "Minuterie en décompte",
        resetToZeroHint: "Remettre le chrono à 00:00",
        resetToStartHint: "Remettre au temps de départ",
        settings: "Paramètres",
        copy: "Message",
        help: "Aide",
        donate: "Soutenir",
        footerAppName: "SannaStudio'Prod Scoreboard",
        changelog: "Mise à jour version 2.9.1",
        detailsTitle: "Paramètres & Annonce",
        detailsDesc: "Personnalisez les paramètres généraux et le texte d'annonce ci-dessous.",
        tagsTitle: "Balises disponibles pour l'annonce",
        keybindsTitle: "Raccourcis clavier",
        keybindsListLabel: "Élément",
        clear: "Effacer",
        actionSettingsTitle: "Paramètres des boutons d'action (Visibilité des sources)",
        actionSettingsDesc: "Définissez les noms, couleurs, hauteur et la source/action OBS cible. La source/groupe doit être dans la scène active.",
        actionSettingsName: "Nom",
        actionSettingsColor: "Couleur",
        actionSettingsHeight: "Hauteur (px)",
        actionSettingsSource: "Nom Source/Groupe",
        actionSettingsAction: "Action",
        actionSettingsEditSave: "Modifier / Sauvegarder",
        keybindsList: [
            { id: "scoreA_plus",      label: "+ Score A (Principal)",       default: "" },
            { id: "scoreA_minus",     label: "- Score A (Principal)",       default: "" },
            { id: "scoreB_plus",      label: "+ Score B (Principal)",       default: "" },
            { id: "scoreB_minus",     label: "- Score B (Principal)",       default: "" },
            { id: "score2A_plus",     label: "+ Score A (Secondaire)",      default: "" },
            { id: "score2A_minus",    label: "- Score A (Secondaire)",      default: "" },
            { id: "score2B_plus",     label: "+ Score B (Secondaire)",      default: "" },
            { id: "score2B_minus",    label: "- Score B (Secondaire)",      default: "" },
            { id: "timer_playpause",  label: "Démarrer / Pauser le chrono", default: "" },
            { id: "timer_resetstart", label: "Remettre au temps de départ", default: "" },
            { id: "timer_togglehalf", label: "Changer de mi-temps",         default: "" },
            { id: "full_reset",       label: "Réinitialisation complète",   default: "" },
        ],
        tagsList: [
            { code: '&lt;TeamA&gt;',         desc: 'Nom Équipe A' },
            { code: '&lt;TeamB&gt;',         desc: 'Nom Équipe B' },
            { code: '&lt;score_team_a&gt;',  desc: 'Score Équipe A' },
            { code: '&lt;score_team_b&gt;',  desc: 'Score Équipe B' },
            { code: '&lt;score2_team_a&gt;', desc: 'Score 2 Équipe A (Fautes/Compteur)' },
            { code: '&lt;score2_team_b&gt;', desc: 'Score 2 Équipe B (Fautes/Compteur)' },
            { code: '&lt;time_counter&gt;',  desc: 'Temps actuel (MM:SS)' },
            { code: '&lt;label1&gt;',        desc: 'Texte Étiquette 1' },
            { code: '&lt;label2&gt;',        desc: 'Texte Étiquette 2' },
            { code: '&lt;label3&gt;',        desc: 'Texte Étiquette 3' },
            { code: '&lt;label4&gt;',        desc: 'Texte Étiquette 4' },
            { code: '&lt;label5&gt;',        desc: 'Texte Étiquette 5' },
        ],
        save: "Sauvegarder",
        settingsTabGeneral:    "📝 Annonce",
        settingsTabActions:    "🎮 Actions",
        settingsTabKeybinds:   "⌨️ Raccourcis",
        settingsTabVisibility: "👁️ Affichage",
        settingsTabData:       "📊 Données",
        confirmResetTitle: "Confirmer la réinitialisation",
        confirmResetMsg: "Ceci réinitialisera tous les scores, le chrono, la mi-temps et le temps additionnel. Êtes-vous sûr ?",
        confirmYes: "Oui, tout réinitialiser",
        confirmNo: "Annuler",
        colorCount:  "Couleurs d'équipe :",
        colorCount1: "1 Couleur",
        colorCount2: "2 Couleurs",
        timerRunning: "En cours",
        timerPaused:  "En pause",
        createObsSources:     "Créer les sources OBS automatiquement",
        createObsSourcesDesc: "Crée automatiquement toutes les sources texte et couleur dans la scène OBS active.",
        toastSourcesCreated:  "Toutes les sources OBS ont été créées avec succès !",
        toastSourcesPartial:  "Certaines sources existaient déjà, les autres ont été créées.",
        toastSourcesFailed:   "Échec de la création des sources. Vérifiez la connexion OBS.",
        helpStep4: "4. Utilisez le bouton <i class='fas fa-cog'></i> Paramètres pour configurer les boutons d'action, raccourcis, affichage et sources de données.",
        helpStep5: "5. Utilisez le bouton <i class='fas fa-mobile-alt'></i> Mobile pour contrôler depuis un smartphone.",
        helpStep6: "6. Cliquez sur <strong>'Créer les sources OBS automatiquement'</strong> ci-dessous pour générer toutes les sources requises.",
        donateShopee:        "Shopee (Affilié)",
        donateDesc:          "Ce programme est gratuit ! Merci pour votre soutien.",
        donateShopeeDesc:    "Soutenez en achetant sur Shopee via ce lien affilié.",
        donateEasyDonateDesc:"Alternative : Soutenir via EasyDonate.",
        donateSponsorTitle:  "Soutenir le développeur",
        donateClose: "Fermer",
        visExtraTimeBtns: "Boutons de temps additionnel",
        visResetToStart:  "Remettre au temps de départ",
        visSetTimeBtn:    "Bouton de réglage du temps",
        visCountdown:     "Décompte",
        visControlTitle:  "Affichage des contrôles du chrono",
        maxHalvesLabel:   "Nombre max de mi-temps :",
        close:         "Fermer",
        saveAndUpdate: "Sauvegarder et mettre à jour",
        helpTitle: "Comment utiliser",
        helpWebSocket: "<strong>Prérequis :</strong> Activez <strong>OBS WebSocket</strong> dans OBS Studio (Outils > Paramètres du serveur WebSocket).<br>Port : <code>4455</code> | <strong>Décochez 'Activer l'authentification'</strong>.",
        helpStep1: "1. Cliquez sur l'icône <i class='fas fa-folder-open'></i> pour définir le chemin du dossier logos. Par défaut : <code>C:/OBSAssets/logos</code>. **Cliquez sur Modifier dans la popup pour changer et sauvegarder le chemin.**",
        helpStep2: "2. Cliquez sur le bouton <i class='fas fa-file-excel'></i> Excel pour sélectionner votre fichier de données (ou utilisez Google Sheets).",
        helpStep3: "3. Sélectionnez l'ID de match souhaité et cliquez sur <i class='fas fa-check'></i> Charger.",
        sourcesTitle: "Sources OBS requises (cliquez pour copier)",
        sourcesTableHeaders: ["Nom de la source", "Type de source", "Détails"],
        selectMatchId: "Sélectionner l'ID de match",
        loadBtn: "CHARGER",
        donateFreeMsg:       "Ce programme est gratuit ! Merci pour votre soutien.",
        donateShopeeMsg:     "Soutenez-moi en achetant sur Shopee via ce lien affilié.",
        donateShopeeAlt:     "QR Code Shopee SannaStudio'Prod",
        donateAltTitle:      "Autres options de soutien",
        donateEasyDonateMsg: "Soutenir via EasyDonate",
        sourcesList: [
            { code: 'Color_Team_A',     type: 'Source Couleur', desc: "Équipe A (Couleur principale)" },
            { code: 'Color_Team_B',     type: 'Source Couleur', desc: "Équipe B (Couleur principale)" },
            { code: 'Color_Team_A_2',   type: 'Source Couleur', desc: "Équipe A (Couleur secondaire)" },
            { code: 'Color_Team_B_2',   type: 'Source Couleur', desc: "Équipe B (Couleur secondaire)" },
            { code: 'logo_team_a',      type: 'Source Image',   desc: "Logo Équipe A" },
            { code: 'logo_team_b',      type: 'Source Image',   desc: "Logo Équipe B" },
            { code: 'name_team_a',      type: 'Texte (GDI+)',   desc: "Nom Équipe A" },
            { code: 'name_team_b',      type: 'Texte (GDI+)',   desc: "Nom Équipe B" },
            { code: 'score_team_a',     type: 'Texte (GDI+)',   desc: "Score Équipe A (Principal)" },
            { code: 'score_team_b',     type: 'Texte (GDI+)',   desc: "Score Équipe B (Principal)" },
            { code: 'score2_team_a',    type: 'Texte (GDI+)',   desc: "Score 2 Équipe A (Fautes/Compteur)" },
            { code: 'score2_team_b',    type: 'Texte (GDI+)',   desc: "Score 2 Équipe B (Fautes/Compteur)" },
            { code: 'label_1',          type: 'Texte (GDI+)',   desc: "Texte Étiquette 1" },
            { code: 'label_2',          type: 'Texte (GDI+)',   desc: "Texte Étiquette 2" },
            { code: 'label_3',          type: 'Texte (GDI+)',   desc: "Texte Étiquette 3" },
            { code: 'label_4',          type: 'Texte (GDI+)',   desc: "Texte Étiquette 4" },
            { code: 'label_5',          type: 'Texte (GDI+)',   desc: "Texte Étiquette 5" },
            { code: 'half_text',        type: 'Texte (GDI+)',   desc: "Mi-temps (1ère/2ème)" },
            { code: 'time_counter',     type: 'Texte (GDI+)',   desc: "Chronomètre" },
            { code: 'injury_time_text', type: 'Texte (GDI+)',   desc: "Temps additionnel (+1)" },
        ],
        understand:          "Compris",
        donateTitle:         "Nous soutenir",
        donateThai:          "Pour les Thaïlandais (pour le Scoreboard)",
        donateForeign:       "Pour l'international",
        timeSettingsTitle:   "Régler le temps de départ",
        timeSettingsMinutes: "Minutes",
        timeSettingsSeconds: "Secondes",
        logoPathTitle: "Chemin du dossier logos & Cache",
        logoPathDesc:  "Le chemin actuel du dossier logos OBS est :",
        logoPathHint:  "Définir le chemin du dossier logos",
        changelogTitle: "Historique des mises à jour",
        changelogContent: `
            <ul class="changelog-list">
                <li>
                    <h5>Version 2.9.1</h5>
                    <ul>
                        <li><strong>Paramètres :</strong> Réorganisés en onglets (Annonce, Actions, Raccourcis, Affichage, Données).</li>
                        <li><strong>Interface :</strong> Sélecteurs de couleur plus grands, option 1 ou 2 couleurs, indicateur d'état du chrono.</li>
                        <li><strong>Expérience :</strong> Confirmation avant réinitialisation complète, Entrée/Échap pour les noms d'équipe, infobulles.</li>
                        <li><strong>OBS :</strong> Création automatique des sources dans la scène active via WebSocket.</li>
                        <li><strong>Corrections :</strong> Flou popup dans OBS Dock, erreurs CSS, viewport meta, positionnement des toasts.</li>
                    </ul>
                </li>
                <li>
                    <h5>Version 2.9</h5>
                    <ul>
                        <li>Compteur d'utilisateurs, design adaptatif, contrôles de visibilité, cache logos, Google Sheets.</li>
                    </ul>
                </li>
            </ul>`,
        toastLoadFileFirst:       "Veuillez d'abord téléverser un fichier",
        toastMatchNotFound:       "ID de match introuvable :",
        toastLoaded:              "ID chargé :",
        toastSuccess:             "Succès",
        toastSwapped:             "Équipes inversées",
        toastNoTextToCopy:        "Aucun texte à copier",
        toastCopied:              "Copié dans le presse-papiers",
        toastCopyFailed:          "Échec de la copie",
        toastScoreReset:          "Score réinitialisé",
        toastScore2Reset:         "Score 2 réinitialisé",
        toastFullReset:           "Tableau de bord entièrement réinitialisé",
        toastCopiedSourceName:    "Nom de source copié :",
        toastSaved:               "Sauvegardé",
        toastKeybindsSaved:       "Raccourci sauvegardé !",
        toastActionSaved:         "Paramètres du bouton d'action sauvegardés !",
        toastColorsCleared:       "Couleurs d'équipe effacées !",
        toastObsError:            "Échec de la connexion à OBS",
        toastActionControlFailed: "Échec du contrôle de la source :",
        toastInvalidTime:         "Format de temps invalide. Vérifiez les minutes et secondes (0-59).",
        toastTimeSet:             "Temps de départ réglé et mis à jour.",
        logoCacheTitle:     "Cache Logos (Affichage Dock UI)",
        logoCacheDesc:      "Glissez-déposez des fichiers image (PNG/JPG) ici pour les afficher dans le Dock UI. Le nom du fichier (sans extension) est la clé du logo.",
        logoDropZoneText:   "Glisser-déposer les fichiers logos ici",
        logoCacheListTitle: "Logos en cache :",
        logoCacheEmpty:     "Aucun logo en cache.",
        logoCacheSaved:     "Logo mis en cache :",
        toastCacheSaveFailed: "Échec de la mise en cache du logo !",
        clearCache:           "Vider le cache logos",
        toastCacheCleared:    "Cache logos vidé !",
        logoCacheSummary: "Résumé de l'importation :",
        logoCacheSuccess: "Réussi :",
        logoCacheFailed:  "Échoué :",
        logoCacheTotal:   "Total en cache :",
        mobileControlTitle: "Contrôle mobile (OBSScore Remote)",
        mobileControlDesc:  "Contrôlez votre tableau de bord depuis un smartphone.",
        createRoom:         "Créer une salle",
        roomName:           "Nom de la salle",
        roomId:             "ID de la salle",
        scanQr:             "Scanner le QR pour se connecter",
        waitingConnection:  "En attente de connexion...",
        connectedDevice:    "Appareil connecté :",
        disconnect:         "Déconnecter",
        openMobileApp:      "Ouvrir l'appli mobile",
        remoteStatus:          "Statut :",
        remoteStatusWait:      "Veille",
        remoteStatusReady:     "Prêt à jumeler",
        remoteStatusConnected: "Connecté",
        dataSourceTitle: "Configuration de la source de données",
        dsExcel:         "Fichier Excel (hors ligne)",
        dsGoogleSheet:   "Google Sheets (en ligne)",
        confirm:                 "Confirmer",
        toastGoogleSheetSuccess: "Google Sheets chargé avec succès !",
        toastGoogleSheetError:   "Échec du chargement. Vérifiez l'URL ou les permissions.",
        loadFromGoogleSheet:     "Récupérer / Recharger GS",
        dsExcelGuide:   "<strong>Guide Excel :</strong> Assurez-vous que votre fichier utilise ces colonnes. Vous pouvez copier les en-têtes ci-dessous. (Les colonnes inutiles peuvent être supprimées)",
        dsColumnList:   "MatchID, LogoA, TeamA, LogoB, TeamB, label1, label2, label3, label4, label5",
        dsCopyColumns:  "Copier les colonnes",
        dsGoogleSheetGuide: "<strong>Guide Google Sheets :</strong><br>1. Cliquez sur <strong>Partager</strong> > Accès général > <strong>Toute personne avec le lien</strong>.<br>2. Cliquez sur <strong>Copier le lien</strong>.<br>3. Collez le lien ci-dessous.<br>4. Retournez à l'écran principal > Cliquez sur <strong>Charger/Récupérer</strong> > Sélectionnez l'ID de match.",
    },
};
